services:
        harmony-frontend:
                build:
                        context: harmony-fe
                        dockerfile: Dockerfile
                ports:
                        - "4200:4200"
                networks:
                        - harmony-network

        harmony-backend:
                build:
                        context: harmony-backend
                        dockerfile: Dockerfile
                ports:
                        - "8080:8080"
                networks:
                        - harmony-network
        
networks:
        harmony-network:
                driver: bridge
