services:
        harmony-frontend:
                build:
                        context: harmony-fe
                        dockerfile: Dockerfile
                networks:
                        - harmony-network

        harmony-backend:
                build:
                        context: harmony-backend
                        dockerfile: Dockerfile
                networks:
                        - harmony-network

        reverse-proxy:
                image: nginx:1.25.2-alpine
                volumes:
                        - ./data/nginx:/etc/nginx/conf.d       
                        - ./data/certbot/conf:/etc/letsencrypt
                        - ./data/certbot/www:/var/www/certbot               
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - harmony-network
                depends_on:
                        - harmony-frontend
                        - harmony-backend
        
networks:
        harmony-network:
                driver: bridge
